# Generated by Django 4.1 on 2022-08-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
