# Generated by Django 4.1 on 2022-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_user_condition_alter_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='condition',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'no covid'), (0, 'covid')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'admin'), (0, 'customer'), (1, 'staff'), (2, 'provider')], null=True),
        ),
    ]
